---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Save interface configuration to the host
#
########################################################################

- name: "Configure /etc/hostname.{{current_iface['dev']}}"
  ansible.builtin.template:
    src: hostname.iface.j2
    dest: "/etc/hostname.{{current_iface['dev']}}"
    owner: root
    group: wheel
    mode: 0640
    backup: true
  become: true
  notify: restart network
